version: "3.9"
    
services:
  mc: 
    image: 42b7cb5fdae8
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - minecraft:/var/lib/docker/volumes
   
volumes:
  minecraft:
